### ISSUE TITLE
Hacktoshin really work Asus X450C ?

### ISSUE THREAD

**Issue by andersoonweb** [febritecno/Sierra_X450CA#1]
Hi @febritecno! Does it really work ? I want install in my notebook!
Follow settings: i3, 6gb ram, 500HD.

Thanks you man.

**Comment by febritecno** [comment]
I use it, and i use ram 6gb and replace wifi card with wifi card supported
osx :)

**Comment by febritecno** [comment]
Hello 👋 too

**Comment by andersoonweb** [comment]
I going try soon!
This repository is awesome, go help-me much.
thanks you man! :smile:

**Comment by febritecno** [comment]
Thanks too
